import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: [
    {
      type: "doc",
      id: "index",
      label: "Readme",
    },
    {
      type: "category",
      label: "Modules",
      link: {
        type: "doc",
        id: "modules",
      },
      collapsible: false,
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "namespaces" }],
    },
  ],
};

export default sidebars;
